INSERT INTO TB_CONTA
(SALDO, LIMITE, CONSUMIDO, DIA_PAGAMENTO_FATURA)
 VALUES
 (4500, 5000, 100, 1);

 INSERT INTO TB_USUARIOS
(NOME, NICK, PASSWORD, STATUS, PERFIL, ID_CONTA)
 VALUES
 ('Arthur', 'teste', '1234', true, 'ROLE_ADMIN', 1);


INSERT INTO TB_TRANSFERENCIA
(DATA_INSERCAO, DATA_LIMITE_PAGAMENTO, TIPO_TRANFERENCIA, VALOR, RESPONSAVEL, ID_CONTA)
 VALUES
 ('2020-04-01', '2020-05-01', 'D', 50, 'Loja X', 1);

INSERT INTO TB_TRANSFERENCIA
(DATA_INSERCAO, DATA_LIMITE_PAGAMENTO, TIPO_TRANFERENCIA, VALOR, RESPONSAVEL, ID_CONTA)
 VALUES
 ('2020-04-01', '2020-05-01', 'D', 50, 'Loja Y', 1);

INSERT INTO TB_TRANSFERENCIA
(DATA_INSERCAO, DATA_LIMITE_PAGAMENTO, TIPO_TRANFERENCIA, VALOR, RESPONSAVEL, ID_CONTA)
 VALUES
 ('2020-04-01', '2020-06-01', 'D', 50, 'Loja Y', 1);

INSERT INTO TB_HISTORICO
(ID_CONTA, NOME_CLIENTE, DATA_TRANSACAO, VALOR_PARCELA, NUMERO_PARCELA, JUROS)
 VALUES
 (1, 'Loja X', '2020-04-01',  50, 1, 0);

INSERT INTO TB_HISTORICO
(ID_CONTA, NOME_CLIENTE, DATA_TRANSACAO, VALOR_PARCELA, NUMERO_PARCELA, JUROS)
 VALUES
 (1, 'Loja Y', '2020-04-01',  50, 2, 0);
