spring.datasource:
   url: jdbc:h2:mem:conta
   data: classpath:db/carga.sql
spring.jpa:
   show-sql: true
   hibernate.ddl-auto: update
spring.h2:
   console:
      enabled: true
      path: /h2-console
jwt:
   secret: fdsfdsfs
   expiration: 86400000