spring.datasource:
   url: jdbc:h2:~/conta;DB_CLOSE_ON_EXIT=FALSE
spring.jpa:
   show-sql: true
   hibernate.ddl-auto: update
spring.h2:
   console:
      enabled: true
      path: /h2-console
jwt:
   secret: fdsfdsfs
   expiration: 86400000